ITEMS = {
    "stone": {
        "name": "Stone",
        "category": "resource",
        "description": "A chunk of solid rock.",
        "rarity": "common",
    },
    "iron": {
        "name": "Iron Ore",
        "category": "resource",
        "description": "Just plain ol' iron ore.",
        "rarity": "common",
    },
    "refined_iron": {
        "name": "Refined Iron",
        "category": "resource",
        "description": "Now its almost good enough to use.",
        "rarity": "uncommon",
    },
    "coal": {
        "name": "Coal",
        "category": "resource",
        "description": "Useful for fuel and forging.",
        "rarity": "common",
    },
    "wood": {
        "name": "Wood",
        "category": "resource",
        "description": "It's just wood.",
        "rarity": "common",
    },
    "oak_wood": {
        "name": "Oak Wood",
        "category": "resource",
        "description": "It's oaky wood.",
        "rarity": "common",
    },
    "corrupted_wood": {
        "name": "Corrupted Wood",
        "category": "resource",
        "description": "It's corrupted wood.",
        "rarity": "uncommon",
    },
    "slime_juice": {
        "name": "Slime Juice",
        "category": "resource",
        "description": "It's sticky...",
        "rarity": "common",
    },
    "ancient_bark": {
        "name": "Ancient Bark",
        "category": "resource",
        "description": "It's barky...",
        "rarity": "uncommon",
    },
    "bone": {
        "name": "Bone",
        "category": "resource",
        "description": "A brittle skeleton bone.",
        "rarity": "common",
    },
    "silk": {
        "name": "Silk",
        "category": "resource",
        "description": "Fine thread from a spider’s abdomen.",
        "rarity": "common",
    },
    "sticky_resin": {
        "name": "Sticky Resin",
        "category": "resource",
        "description": "Tough organic glue harvested from cocoons.",
        "rarity": "uncommon",
    },
    "spider_fang": {
        "name": "Spider Fang",
        "category": "resource",
        "description": "Still dripping with venom.",
        "rarity": "uncommon",
    },
    "rotten_flesh": {
        "name": "Rotten Flesh",
        "category": "resource",
        "description": "Not particularly appetizing.",
        "rarity": "common",
    },
    "corrupted_essence": {
        "name": "Corrupted Essence",
        "category": "resource",
        "description": "Corrupted something something.",
        "rarity": "rare",
    },
    "slime_essence": {
        "name": "Slime Essence",
        "category": "resource",
        "description": "Refined slimes. Yummy.",
        "rarity": "uncommon",
    },
    "slime_soul": {
        "name": "Slime Soul",
        "category": "resource",
        "description": "The remnents of a strong green one.",
        "rarity": "legendary",
    },
    "tree_soul": {
        "name": "Tree Soul",
        "category": "resource",
        "description": "The remnents of a strong barky one.",
        "rarity": "legendary",
    },
    "silk_soul": {
        "name": "Silk Soul",
        "category": "resource",
        "description": "The remnents of silk.",
        "rarity": "legendary",
    },
    "bone_soul": {
        "name": "Bone Soul",
        "category": "resource",
        "description": "The remnents of a bony one.",
        "rarity": "legendary",
    },
    "zombie_soul": {
        "name": "Zombie Soul",
        "category": "resource",
        "description": "The remnents of a rotten one.",
        "rarity": "legendary",
    },
    "slime_core": {
        "name": "Slime Core",
        "category": "resource",
        "description": "Dense magical blob with strange properties.",
        "rarity": "uncommon",
    },
    "slime_crown": {
        "name": "Slime Crown",
        "category": "Armour",
        "description": "Once worn by the royal slime.",
        "rarity": "legendary",
        "slot": "head",
        "set": "slime_set",
        "stat_bonuses": {"strength": 100,
                         "crit_damage": 100},
    },
    "slime_chest": {
        "name": "Slime Chest",
        "category": "Armour",
        "description": "Once worn by the royal slime.",
        "rarity": "legendary",
        "slot": "body",
        "set": "slime_set",
        "stat_bonuses": {"strength": 100,
                         "crit_damage": 100},
    },
    "slime_legs": {
        "name": "Slime Legs",
        "category": "Armour",
        "description": "Once worn by the royal slime.",
        "rarity": "legendary",
        "slot": "legs",
        "set": "slime_set",
        "stat_bonuses": {"strength": 100,
                         "crit_damage": 100},
    },
    "slime_boots": {
        "name": "Slime Boots",
        "category": "Armour",
        "description": "Once worn by the royal slime.",
        "rarity": "legendary",
        "slot": "feet",
        "set": "slime_set",
        "stat_bonuses": {"strength": 100,
                         "crit_damage": 100},
    },
    "slime_gloves": {
        "name": "Slime Gloves",
        "category": "Armour",
        "description": "Once worn by the royal slime.",
        "rarity": "legendary",
        "slot": "hands",
        "set": "slime_set",
        "stat_bonuses": {"strength": 100,
                         "crit_damage": 100},
    },
    "wooden_axe": {
        "name": "Wooden Axe",
        "category": "tool",
        "description": "Used for chopping wood.",
        "rarity": "common",
        "skill": "woodcutting",
        "radius": 70, 
        "delay": 800, 
    },
    "iron_axe": {
        "name": "Iron Axe",
        "category": "tool",
        "description": "Used for chopping wood faster.",
        "rarity": "uncommon",
        "skill": "woodcutting",
        "radius": 70, 
        "delay": 700, 
    },
    "corrupted_axe": {
        "name": "Corrupted Axe",
        "category": "tool",
        "description": "Used for chopping wood faster faster.",
        "rarity": "rare",
        "skill": "woodcutting",
        "radius": 70, 
        "delay": 600, 
    },
    "old_sword": {
        "name": "Old Sword",
        "category": "weapon",
        "description": "Once wielded by brave hero",
        "rarity": "uncommon",
        "skill": "combat",
        "radius": 40, 
        "delay": 900, 
        "weapon": {"damage": 30},
        "stat_bonuses": {"strength": 20, "crit_chance": 5},
    },
    "stormblade": {
        "name": "Stormblade",
        "category": "weapon",
        "description": "Crackling with latent power.",
        "rarity": "epic",
        "skill": "combat",
        "radius": 50,
        "delay": 800,
        "weapon": {"damage": 60},
        "stat_bonuses": {
            "strength": 30,
            "crit_chance": 10,
        },
        "counter_id": "piercing_storm"
    },
    "axe_of_thorns": {
        "name": "Axe of Thorns",
        "category": "weapon",
        "description": "Ouch!",
        "rarity": "epic",
        "skill": "combat",
        "radius": 60,
        "delay": 850,
        "weapon": {"damage": 50},
        "stat_bonuses": {
            "strength": 25,
            "attack_speed": 20,
        },
        "counter_id": "needle_dread"
    },
    "iron_maul": {
        "name": "Iron Maul",
        "category": "weapon",
        "description": "Heavy, slow, and effective.",
        "rarity": "uncommon",
        "skill": "combat",
        "radius": 50, 
        "delay": 1200, 
        "weapon": { "damage": 50 },
        "stat_bonuses": {
            "strength": 40,
            "attack_speed": -20,
        },
    },
    "iron_dagger": {
        "name": "Iron Dagger",
        "category": "weapon",
        "description": "Fast, a little blunt, maybe deadly?",
        "rarity": "uncommon",
        "skill": "combat",
        "radius": 35, 
        "delay": 700,
        "weapon": { "damage": 20 },
        "stat_bonuses": {
            "strength": 10,
            "attack_speed": 25,
            "crit_chance": 10,
            "crit_damage": 25,
        },
    },
    "chimp_sword": {
        "name": "Chimp Sword",
        "category": "weapon",
        "description": "Monkey Goggins sits in the corner. Watching.",
        "rarity": "mythic",
        "skill": "combat",
        "radius": 100, 
        "delay": 700, 
        "weapon": {"damage": 100},
        "stat_bonuses": {
            "strength": 50,
            "crit_chance": 50,
            "crit_damage": 150,
            "attack_speed": 200,
        },
    },
    "slime_sword": {
        "name": "Slime Sword",
        "category": "weapon",
        "description": "Once wielded by Sir Slime himself.",
        "rarity": "rare",
        "skill": "combat",
        "radius": 50, 
        "delay": 900, 
        "weapon": {"damage": 35},
        "stat_bonuses": {"strength": 10, "crit_chance": 5},
    },
    "wooden_pickaxe": {
        "name": "Wooden Pickaxe",
        "category": "tool",
        "description": "A basic mining tool.",
        "rarity": "common",
        "skill": "mining",
        "stat_bonuses": {},
        "radius": 45,
        "delay": 800,
    },
    "iron_pickaxe": {
        "name": "Iron Pickaxe",
        "category": "tool",
        "description": "A better mining tool. and this is a mega long description skibidi rizzler pog champ",
        "rarity": "uncommon",
        "skill": "mining",
        "stat_bonuses": {},
        "radius": 50,
        "delay": 700,
    },
    "globbulite_pickaxe": {
        "name": "Globbulite Pickaxe",
        "category": "tool",
        "description": "An even better mining tool. and this is a mega long description skibidi rizzler pog champ",
        "rarity": "rare",
        "skill": "mining",
        "stat_bonuses": {},
        "radius": 55,
        "delay": 600,
    },
    "leather_helmet": {
        "name": "Leather Helmet",
        "category": "Armour",
        "description": "Offers light protection for the head.",
        "rarity": "uncommon",
        "slot": "head",
        "stat_bonuses": {
            "max_hp": 5,
            "defense": 5
        }
    },
    "leather_chestplate": {
        "name": "Leather Chestplate",
        "category": "Armour",
        "description": "Provides modest body protection.",
        "rarity": "uncommon",
        "slot": "body",
        "stat_bonuses": {
            "max_hp": 5,
            "defense": 5
        }
    },
    "leather_boots": {
        "name": "Leather Boots",
        "category": "Armour",
        "description": "Keeps your feet dry. Adds slight toughness.",
        "rarity": "uncommon",
        "slot": "feet",
        "stat_bonuses": {
            "max_hp": 5,
            "defense": 5
        }
    },
    "bone_plate": {
        "name": "Bone Plate",
        "category": "Armour",
        "description": "A heavy chestplate made from fossilized bone.",
        "rarity": "rare",
        "slot": "body",
        "stat_bonuses": {"max_hp": 50, "defense": 20}
    },
    "ghoulish_greaves": {
        "name": "Ghoulish Greaves",
        "category": "Armour",
        "description": "Hardy and speedy.",
        "rarity": "rare",
        "slot": "legs",
        "stat_bonuses": {
            "defense": 15, 
            "speed": 25,
        }
    },
    "silk_striders": {
        "name": "Silk Striders",
        "category": "Armour",
        "description": "Delicate boots enhancing your speed.",
        "rarity": "rare",
        "slot": "feet",
        "stat_bonuses": {
            "speed": 50, 
            "crit_chance": 5,
            "attack_speed": 20,
        }
    },
    "grandmas_mittens": {
        "name": "Grandma's Mittens",
        "category": "Armour",
        "description": "They have baked untold numbers of cookies.",
        "rarity": "legendary",
        "slot": "hands",
        "stat_bonuses": {
            "attack_speed": 100,
        }
    },
    "fang_dagger": {
        "name": "Fang Dagger",
        "category": "weapon",
        "description": "A blade made of piercing fangs.",
        "rarity": "epic",
        "stat_bonuses": {
            "strength": 50,
            "crit_chance": 10,
            "crit_damage": 50,
        },
        "weapon": {"damage": 75},
        "radius": 60,
        "delay": 700,
        "skill": "combat"
    },
    "boots_of_speed": {
        "name": "Boots of Speed",
        "category": "Armour",
        "description": "Flash.",
        "rarity": "legendary",
        "slot": "feet",
        "stat_bonuses": {
            "speed": 100, 
        }
    },
    "mantle_of_mending": {
        "name": "Mantle of Mending",
        "category": "Armour",
        "description": "An old robe imbued with healing powers.",
        "rarity": "legendary",
        "slot": "body",
        "stat_bonuses": {
            "max_hp": 100,
            "vitality": 10, 
        }
    },
    "phoenix_crown": {
        "name": "Phoenix Crown",
        "category": "Armour",
        "description": "Crown imbued with the essence of the phoenix.",
        "rarity": "legendary",
        "slot": "head",
        "set": "phoenix_set",
        "stat_bonuses": {
            "strength": 25,
        },
    },
    "phoenix_chest": {
        "name": "Phoenix Chest",
        "category": "Armour",
        "description": "Chestplate burning with inner flame.",
        "rarity": "legendary",
        "slot": "body",
        "set": "phoenix_set",
        "stat_bonuses": {
            "speed": 10,
            "max_hp": 50,
        },
    },
    "phoenix_legs": {
        "name": "Phoenix Legs",
        "category": "Armour",
        "description": "Leggings warm to the touch.",
        "rarity": "legendary",
        "slot": "legs",
        "set": "phoenix_set",
        "stat_bonuses": {
            "strength": 50,
            "max_hp": 100,
        },
    },
    "phoenix_boots": {
        "name": "Phoenix Boots",
        "category": "Armour",
        "description": "Boots trailing embers with each step.",
        "rarity": "legendary",
        "slot": "feet",
        "set": "phoenix_set",
        "stat_bonuses": {
            "strength": 25,
            "speed": 20,
        }, 
    },
}

NULL_ITEM = {"name": "Unknown Item", "category": "Unknown", "description": "No description available.", "rarity": "mythic"}