RESOURCE_NODE_TYPES = [
    {
        "id": "stone",
        "name": "Stone Node",
        "skill": "mining",
        "colour": (120, 120, 120),
        "size": 25,
        "hp": 3,
        "reward_xp": 12,
        "drop_table": [("stone", 1.0, (3, 5))],
    },
    {
        "id": "tree",
        "name": "Tree",
        "skill": "woodcutting",
        "colour": (140, 70, 20),
        "size": 50,
        "hp": 10,
        "reward_xp": 50,
        "drop_table": [("wood", 1.0, (5, 8))],
    },
    {
        "id": "oak_tree",
        "name": "Oak Tree",
        "skill": "woodcutting",
        "colour": (130, 60, 20),
        "size": 45,
        "hp": 12,
        "reward_xp": 84,
        "drop_table": [("oak_wood", 1.0, (5, 8))],
    },
    {
        "id": "oak_tree",
        "name": "Oak Tree",
        "skill": "woodcutting",
        "colour": (130, 60, 20),
        "size": 45,
        "hp": 12,
        "reward_xp": 84,
        "drop_table": [("oak_wood", 1.0, (5, 8))],
        "required_skills": {"woodcutting": 5},
    },
    {
        "id": "corrupted_tree",
        "name": "Corrupted Tree",
        "skill": "woodcutting",
        "colour": (180, 50, 20),
        "size": 35,
        "hp": 15,
        "reward_xp": 180,
        "drop_table": [("corrupted_wood", 1.0, (3, 5))],
        "required_skills": {"woodcutting": 10},
    },
    {
        "id": "coal",
        "name": "Coal Node",
        "skill": "mining",
        "colour": (10, 10, 10),
        "size": 25,
        "hp": 4,
        "reward_xp": 28,
        "drop_table": [("coal", 1.0)],
        "required_skills": {"mining": 3},
    },
    {
        "id": "iron",
        "name": "Iron Node",
        "skill": "mining",
        "colour": (180, 100, 60),
        "size": 40,
        "hp": 5,
        "reward_xp": 50,
        "drop_table": [("iron", 1.0)],
        "required_skills": {"mining": 5},
    },
    {
        "id": "web_cocoon",
        "name": "Web Cocoon",
        "skill": "mining",
        "colour": (180, 180, 255),
        "size": 10,
        "hp": 1,
        "reward_xp": 5,
        "drop_table": {
            "common": [("silk", 1.0)],
            "rare": [("sticky_resin", 0.03)],
        },
        "required_skills": {"mining": 1},
    },
    {
        "id": "bone_pile",
        "name": "Bone Pile",
        "skill": "mining",
        "colour": (200, 200, 200),
        "size": 25,
        "hp": 1,
        "reward_xp": 5,
        "drop_table": [("bone", 1.0)],
        "required_skills": {"mining": 1},
    },
]

RESOURCE_NODE_LOOKUP = {node["id"]: node for node in RESOURCE_NODE_TYPES}
